config/routes.rb
Rails.application.routes.draw do
  get 'products/index'

   root 'products#index'
   resources :products
   resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :products, dependent: :destroy 
	validates :name, presence: true 
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :product

	has_attached_file :image, 
		styles: {thumbnail: "60*60>", medium: "300*300>", large: "600*600>"},
	 	default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates_attachment_presence :image
	#validates_attachment_size :image, less_than: 5megabytes

end

app/models/product.rb
class Product < ActiveRecord::Base

	#Associations
	belongs_to :category
	has_many :photos, dependent: :destroy
	#accepts_nested_attributes_for :photos,:reject_if => lambda {|t| t['image'].nil? }

	#Validations
	validates :name, presence: true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ProductsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	respond_to :html, :js

	def create
		@category = Category.new(name: params[:name])
		if @category.save
			render json: {category: @category, status: "success"}
		else
			render json: {status: "fails"}
		end
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @categories = Category.order("name ASC")
    category_sidebar
  end

  def new
  	@product = Product.new
    @category = Category.new
  	@product.photos.build
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
      if !params[:image].blank?
        params[:image].each do |img|
          @product.photos.create(image: img)
        end
      end
  		redirect_to @product
  	else
  		render 'new'
  	end
  end

  def product_by_category
    render 'index'
  end

# Private methods
  private

  def product_params
  	params.require(:product).permit(:name, :price, :desc, :category_id,
                    :photos_attributes => [:id,:image])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def category_sidebar
		if params[:cat_type]
      		@products = Category.find(params[:cat_type].to_i).products
    	else
    		@products = Product.all.order("name ASC")
    	end
	end
end

app/views/categories/create.js.erb
//$('#product_category_id').append('<option>').text(@category.name).value(@category.id.to_s);

app/views/categories/index.html.erb
<div class="product_form">
<div class="container">
<% @categories.each_slice(3) do |categories| %>
<div class="row">
	<%= categories.each do |cat| %>
		<div class="col">
			<%= cat.name %>
		</div>
	<% end %>
</div>
<% end %>
</div>
</div>

app/views/categories/new.html.erb
<div class="product_form">
<h1> New Category</h1>
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 col-xs-10 col-xs-offset-1">

<%= form_for @category do |f| %>
	<%= render "shared/error_messages", product: f.object %>
	<%= f.label :name %>
	<%= f.text_field :name, class: "form-control" %>
	<%= f.submit "Add", class: "btn btn-primary form-submit-button" %>
<% end %>

</div>
</div>
</div>
<div>

app/views/categories/show.js.erb
$("#new_product").html("<% j(render @product %>"))

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mycart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
  	
  </script>
</head>
<body>
<%= render "shared/header" %>

<%= yield %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/products/_category_modal.html.erb
<div id="modal-content" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>Add Category</h3>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <%= label_tag "name" %>
                    <%= text_field_tag "name", nil, id: "category_name" %>
                </div>

                <div class="modal-footer"> 
                    <a href="#" class="btn" data-dismiss="modal">Close</a>
                    <%= link_to "Add", "#", class: "btn btn-primary add-category-ajax" %>
                </div>

        
            </div>
            
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="product_form">
<div id="custom-sidebar" class="sidebar">
	<ul id="nav nav-sidebar" class="category-list" >
		<% @categories.each do |category| %>
			<li>
				<%= link_to category.name, root_path(:cat_type => category.id) %>
			</li>
		<% end %>
	</ul>
</div>

<div id="product-content">
<ul id="product-list">
		<% @products.each_slice(3) do |products| %>
			<div class="row product-row">
				<% products.each do |product| %>
					<div class="col-md-3 col-md-offset-1 product-col">
						<div class="product-image">
							<% if product.photos.present? && product.photos.first.image.present? %>
									<%= link_to image_tag(product.photos.first.image.url(:thumbnail)), product, class: "img-responsive" %>
							<% else %>
									<%= link_to image_tag("/images/thumbnail/missing.png", size: "20*20"), product,class: "img-responsive" %>
							<%end %>
					</div>

					<div class="product-name">
							<%= link_to product.name, product %>
					</div>
					<div class="product-price">
							Rs. <%= product.price %>
					</div>

					</div>
				<% end %>
			</div>
		<% end %>
</ul>
</div>
</div>

app/views/products/new.html.erb
<div class="product_form">
<%= render 'category_modal' %>
<h1> New Product </h1>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 col-xs-10 col-xs-offset-1">
			<%= form_for @product, html: { multipart: true } do |f| %>
				<%= render "shared/error_messages", product: f.object %>

				<div class="form-group">
					<%= f.label :category %>
					<%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true, class: "form-control" %>					
					<%= link_to "Add Category", "#",id: "add-category" %>
				</div>

				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :price %>
					<%= f.text_field :price, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :desc, "Description" %>
					<%=	f.text_area :desc, rows: 5, cols: 30, class: "form-control"  %>
				</div>

				<div class="form-group">
						<%= label_tag "Add Photo" %>
						<%= file_field_tag "image[]", type: :file, multiple: true %>
				</div>

				<div class="form-group">
					<%= f.submit "Add", class: "btn btn-primary form-submit-button" %>
				</div>

			<% end %>
		</div>
	</div>
</div>
</div>

app/views/products/show.html.erb
<div class="product_form">
<h3>Name: <%= @product.name %> </h3>
<h3>Price: <%= @product.price %> </h3>

<div>
<% if @product.photos %>
	<% @product.photos.each_slice(3) do |photos| %>
		<div class="row">
		<% photos.each do |p| %>
			<span class="col-md-2 col-md-offset-1">
				<%= image_tag p.image.url(:medium) %>
			</span>
		<% end %>
		</div>
	<% end %>
<% end %>
</div>
<hr>
<h5>Description: <%= @product.desc %> </h5>
</div>

app/views/shared/_category_list.html.erb
<% if categories.any? %>
	<ul>
		<% categories.each do |category| %>
			<li>
				<%= category %>
			</li>
		<% end %>
	</ul>
<% end %>

app/views/shared/_error_messages.html.erb
<% if product.errors.any? %>
<div class= "alert alert-danger">
	<ul>
		<% product.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "MyCart", root_path, id: "logo" %>

		<nav>
			<ul class="nav navbar navbar-right">
				<li>
				<%= link_to "Create Product", new_product_path,class: "btn btn-default btn-md", id: "create-product-button" %>
				</li>
			</ul>
		</nav>

	</div>
</header>